<?php


use App\Models\City;
use App\Models\County;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared(file_get_contents(database_path('seeds/sql/city_district.sql')));
    }

    private function cities()
    {
        $cities = [
            ['id' => 1, 'title' => 'Adana'],
            ['id' => 2, 'title' => 'Adıyaman'],
            ['id' => 3, 'title' => 'Afyonkarahisar'],
            ['id' => 4, 'title' => 'Ağrı'],
            ['id' => 5, 'title' => 'Aksaray'],
            ['id' => 6, 'title' => 'Amasya'],
            ['id' => 7, 'title' => 'Ankara'],
            ['id' => 8, 'title' => 'Antalya'],
            ['id' => 9, 'title' => 'Ardahan'],
            ['id' => 10, 'title' => 'Artvin'],
            ['id' => 11, 'title' => 'Aydın'],
            ['id' => 12, 'title' => 'Balıkesir'],
            ['id' => 13, 'title' => 'Bartın'],
            ['id' => 14, 'title' => 'Batman'],
            ['id' => 15, 'title' => 'Bayburt'],
            ['id' => 16, 'title' => 'Bilecik'],
            ['id' => 17, 'title' => 'Bingöl'],
            ['id' => 18, 'title' => 'Bitlis'],
            ['id' => 19, 'title' => 'Bolu'],
            ['id' => 20, 'title' => 'Burdur'],
            ['id' => 21, 'title' => 'Bursa'],
            ['id' => 22, 'title' => 'Çanakkale'],
            ['id' => 23, 'title' => 'Çankırı'],
            ['id' => 24, 'title' => 'Çorum'],
            ['id' => 25, 'title' => 'Denizli'],
            ['id' => 26, 'title' => 'Diyarbakır'],
            ['id' => 27, 'title' => 'Düzce'],
            ['id' => 28, 'title' => 'Edirne'],
            ['id' => 29, 'title' => 'Elazığ'],
            ['id' => 30, 'title' => 'Erzincan'],
            ['id' => 31, 'title' => 'Erzurum'],
            ['id' => 32, 'title' => 'Eskişehir'],
            ['id' => 33, 'title' => 'Gaziantep'],
            ['id' => 34, 'title' => 'Giresun'],
            ['id' => 35, 'title' => 'Gümüşhane'],
            ['id' => 36, 'title' => 'Hakkari'],
            ['id' => 37, 'title' => 'Hatay'],
            ['id' => 38, 'title' => 'İğdır'],
            ['id' => 39, 'title' => 'İsparta'],
            ['id' => 40, 'title' => 'İstanbul'],
            ['id' => 41, 'title' => 'İzmir'],
            ['id' => 42, 'title' => 'Kahramanmaraş'],
            ['id' => 43, 'title' => 'Karabük'],
            ['id' => 44, 'title' => 'Karaman'],
            ['id' => 45, 'title' => 'Kars'],
            ['id' => 46, 'title' => 'Kastamonu'],
            ['id' => 47, 'title' => 'Kayseri'],
            ['id' => 48, 'title' => 'Kilis'],
            ['id' => 49, 'title' => 'Kırıkkale'],
            ['id' => 50, 'title' => 'Kırklareli'],
            ['id' => 51, 'title' => 'Kırşehir'],
            ['id' => 52, 'title' => 'Kocaeli'],
            ['id' => 53, 'title' => 'Konya'],
            ['id' => 54, 'title' => 'Kütahya'],
            ['id' => 55, 'title' => 'Malatya'],
            ['id' => 56, 'title' => 'Manisa'],
            ['id' => 57, 'title' => 'Mardin'],
            ['id' => 58, 'title' => 'Mersin'],
            ['id' => 59, 'title' => 'Muğla'],
            ['id' => 60, 'title' => 'Muş'],
            ['id' => 61, 'title' => 'Nevşehir'],
            ['id' => 62, 'title' => 'Niğde'],
            ['id' => 63, 'title' => 'Ordu'],
            ['id' => 64, 'title' => 'Osmaniye'],
            ['id' => 65, 'title' => 'Rize'],
            ['id' => 66, 'title' => 'Sakarya'],
            ['id' => 67, 'title' => 'Samsun'],
            ['id' => 68, 'title' => 'Şanlıurfa'],
            ['id' => 69, 'title' => 'Siirt'],
            ['id' => 70, 'title' => 'Sinop'],
            ['id' => 71, 'title' => 'Şırnak'],
            ['id' => 72, 'title' => 'Sivas'],
            ['id' => 73, 'title' => 'Tekirdağ'],
            ['id' => 74, 'title' => 'Tokat'],
            ['id' => 75, 'title' => 'Trabzon'],
            ['id' => 76, 'title' => 'Tunceli'],
            ['id' => 77, 'title' => 'Uşak'],
            ['id' => 78, 'title' => 'Van'],
            ['id' => 79, 'title' => 'Yalova'],
            ['id' => 80, 'title' => 'Yozgat'],
            ['id' => 81, 'title' => 'Zonguldak'],
        ];

        foreach ($cities as $data) {
            City::create($data);
        }
    }

    private function districts()
    {
        $districts = [
            ['id' => 1, 'title' => 'Aladağ', 'city_id' => 1],
            ['id' => 2, 'title' => 'Ceyhan', 'city_id' => 1],
            ['id' => 3, 'title' => 'Çukurova', 'city_id' => 1],
            ['id' => 4, 'title' => 'Feke', 'city_id' => 1],
            ['id' => 5, 'title' => 'İmamoğlu', 'city_id' => 1],
            ['id' => 6, 'title' => 'Karaisali', 'city_id' => 1],
            ['id' => 7, 'title' => 'Karataş', 'city_id' => 1],
            ['id' => 8, 'title' => 'Kozan', 'city_id' => 1],
            ['id' => 9, 'title' => 'Pozanti', 'city_id' => 1],
            ['id' => 10, 'title' => 'Saimbeyli', 'city_id' => 1],
            ['id' => 11, 'title' => 'Sariçam', 'city_id' => 1],
            ['id' => 12, 'title' => 'Seyhan', 'city_id' => 1],
            ['id' => 13, 'title' => 'Tufanbeyli', 'city_id' => 1],
            ['id' => 14, 'title' => 'Yumurtalik', 'city_id' => 1],
            ['id' => 15, 'title' => 'Yüreğir', 'city_id' => 1],
            ['id' => 16, 'title' => 'Besni', 'city_id' => 2],
            ['id' => 17, 'title' => 'Çelikhan', 'city_id' => 2],
            ['id' => 18, 'title' => 'Gerger', 'city_id' => 2],
            ['id' => 19, 'title' => 'Gölbaşi', 'city_id' => 2],
            ['id' => 20, 'title' => 'Kahta', 'city_id' => 2],
            ['id' => 21, 'title' => 'Adiyaman', 'city_id' => 2],
            ['id' => 22, 'title' => 'Samsat', 'city_id' => 2],
            ['id' => 23, 'title' => 'Sincik', 'city_id' => 2],
            ['id' => 24, 'title' => 'Tut', 'city_id' => 2],
            ['id' => 25, 'title' => 'Afyonkarahisar', 'city_id' => 3],
            ['id' => 26, 'title' => 'Başmakçi', 'city_id' => 3],
            ['id' => 27, 'title' => 'Bayat', 'city_id' => 3],
            ['id' => 28, 'title' => 'Bolvadin', 'city_id' => 3],
            ['id' => 29, 'title' => 'Çay', 'city_id' => 3],
            ['id' => 30, 'title' => 'Çobanlar', 'city_id' => 3],
            ['id' => 31, 'title' => 'Dazkiri', 'city_id' => 3],
            ['id' => 32, 'title' => 'Dinar', 'city_id' => 3],
            ['id' => 33, 'title' => 'Emirdağ', 'city_id' => 3],
            ['id' => 34, 'title' => 'Evciler', 'city_id' => 3],
            ['id' => 35, 'title' => 'Hocalar', 'city_id' => 3],
            ['id' => 36, 'title' => 'İhsaniye', 'city_id' => 3],
            ['id' => 37, 'title' => 'İscehisar', 'city_id' => 3],
            ['id' => 38, 'title' => 'Kizilören', 'city_id' => 3],
            ['id' => 39, 'title' => 'Sandikli', 'city_id' => 3],
            ['id' => 40, 'title' => 'Sinanpaşa', 'city_id' => 3],
            ['id' => 41, 'title' => 'Şuhut', 'city_id' => 3],
            ['id' => 42, 'title' => 'Sultandaği', 'city_id' => 3],
            ['id' => 43, 'title' => 'Diyadin', 'city_id' => 4],
            ['id' => 44, 'title' => 'Doğubeyazit', 'city_id' => 4],
            ['id' => 45, 'title' => 'Eleşkirt', 'city_id' => 4],
            ['id' => 46, 'title' => 'Hamur', 'city_id' => 4],
            ['id' => 47, 'title' => 'Ağri', 'city_id' => 4],
            ['id' => 48, 'title' => 'Patnos', 'city_id' => 4],
            ['id' => 49, 'title' => 'Taşliçay', 'city_id' => 4],
            ['id' => 50, 'title' => 'Tutak', 'city_id' => 4],
            ['id' => 51, 'title' => 'Ağaçören', 'city_id' => 5],
            ['id' => 52, 'title' => 'Eskil', 'city_id' => 5],
            ['id' => 53, 'title' => 'Gülağaç', 'city_id' => 5],
            ['id' => 54, 'title' => 'Güzelyurt', 'city_id' => 5],
            ['id' => 55, 'title' => 'Aksaray', 'city_id' => 5],
            ['id' => 56, 'title' => 'Ortaköy', 'city_id' => 5],
            ['id' => 57, 'title' => 'Sariyahşi', 'city_id' => 5],
            ['id' => 58, 'title' => 'Göynücek', 'city_id' => 6],
            ['id' => 59, 'title' => 'Gümüşhaciköy', 'city_id' => 6],
            ['id' => 60, 'title' => 'Hamamözü', 'city_id' => 6],
            ['id' => 61, 'title' => 'Amasya', 'city_id' => 6],
            ['id' => 62, 'title' => 'Merzifon', 'city_id' => 6],
            ['id' => 63, 'title' => 'Suluova', 'city_id' => 6],
            ['id' => 64, 'title' => 'Taşova', 'city_id' => 6],
            ['id' => 65, 'title' => 'Akyurt', 'city_id' => 7],
            ['id' => 66, 'title' => 'Altindağ', 'city_id' => 7],
            ['id' => 67, 'title' => 'Ayaş', 'city_id' => 7],
            ['id' => 68, 'title' => 'Bala', 'city_id' => 7],
            ['id' => 69, 'title' => 'Beypazari', 'city_id' => 7],
            ['id' => 70, 'title' => 'Çamlidere', 'city_id' => 7],
            ['id' => 71, 'title' => 'Çankaya', 'city_id' => 7],
            ['id' => 72, 'title' => 'Çubuk', 'city_id' => 7],
            ['id' => 73, 'title' => 'Elmadağ', 'city_id' => 7],
            ['id' => 74, 'title' => 'Etimesgut', 'city_id' => 7],
            ['id' => 75, 'title' => 'Evren', 'city_id' => 7],
            ['id' => 76, 'title' => 'Gölbaşi', 'city_id' => 7],
            ['id' => 77, 'title' => 'Güdül', 'city_id' => 7],
            ['id' => 78, 'title' => 'Haymana', 'city_id' => 7],
            ['id' => 79, 'title' => 'Kalecik', 'city_id' => 7],
            ['id' => 80, 'title' => 'Kazan', 'city_id' => 7],
            ['id' => 81, 'title' => 'Keçiören', 'city_id' => 7],
            ['id' => 82, 'title' => 'Kizilcahamam', 'city_id' => 7],
            ['id' => 83, 'title' => 'Mamak', 'city_id' => 7],
            ['id' => 84, 'title' => 'Nallihan', 'city_id' => 7],
            ['id' => 85, 'title' => 'Polatli', 'city_id' => 7],
            ['id' => 86, 'title' => 'Pursaklar', 'city_id' => 7],
            ['id' => 87, 'title' => 'Şereflikoçhisar', 'city_id' => 7],
            ['id' => 88, 'title' => 'Sincan', 'city_id' => 7],
            ['id' => 89, 'title' => 'Yenimahalle', 'city_id' => 7],
            ['id' => 90, 'title' => 'Akseki', 'city_id' => 8],
            ['id' => 91, 'title' => 'Aksu', 'city_id' => 8],
            ['id' => 92, 'title' => 'Alanya', 'city_id' => 8],
            ['id' => 93, 'title' => 'Döşemealti', 'city_id' => 8],
            ['id' => 94, 'title' => 'Elmali', 'city_id' => 8],
            ['id' => 95, 'title' => 'Finike', 'city_id' => 8],
            ['id' => 96, 'title' => 'Gazipaşa', 'city_id' => 8],
            ['id' => 97, 'title' => 'Gündoğmuş', 'city_id' => 8],
            ['id' => 98, 'title' => 'İbradi', 'city_id' => 8],
            ['id' => 99, 'title' => 'Kale', 'city_id' => 8],
            ['id' => 100, 'title' => 'Kaş', 'city_id' => 8],
            ['id' => 101, 'title' => 'Kemer', 'city_id' => 8],
            ['id' => 102, 'title' => 'Kepez', 'city_id' => 8],
            ['id' => 103, 'title' => 'Konyaalti', 'city_id' => 8],
            ['id' => 104, 'title' => 'Korkuteli', 'city_id' => 8],
            ['id' => 105, 'title' => 'Kumluca', 'city_id' => 8],
            ['id' => 106, 'title' => 'Manavgat', 'city_id' => 8],
            ['id' => 107, 'title' => 'Muratpaşa', 'city_id' => 8],
            ['id' => 108, 'title' => 'Serik', 'city_id' => 8],
            ['id' => 109, 'title' => 'Çildir', 'city_id' => 9],
            ['id' => 110, 'title' => 'Damal', 'city_id' => 9],
            ['id' => 111, 'title' => 'Göle', 'city_id' => 9],
            ['id' => 112, 'title' => 'Hanak', 'city_id' => 9],
            ['id' => 113, 'title' => 'Ardahan', 'city_id' => 9],
            ['id' => 114, 'title' => 'Posof', 'city_id' => 9],
            ['id' => 115, 'title' => 'Ardanuç', 'city_id' => 10],
            ['id' => 116, 'title' => 'Arhavi', 'city_id' => 10],
            ['id' => 117, 'title' => 'Borkça', 'city_id' => 10],
            ['id' => 118, 'title' => 'Hopa', 'city_id' => 10],
            ['id' => 119, 'title' => 'Artvin', 'city_id' => 10],
            ['id' => 120, 'title' => 'Murgul', 'city_id' => 10],
            ['id' => 121, 'title' => 'Şavşat', 'city_id' => 10],
            ['id' => 122, 'title' => 'Yusufeli', 'city_id' => 10],
            ['id' => 123, 'title' => 'Bozdoğan', 'city_id' => 11],
            ['id' => 124, 'title' => 'Buharkent', 'city_id' => 11],
            ['id' => 125, 'title' => 'Çine', 'city_id' => 11],
            ['id' => 126, 'title' => 'Didim', 'city_id' => 11],
            ['id' => 127, 'title' => 'Germencik', 'city_id' => 11],
            ['id' => 128, 'title' => 'İncirliova', 'city_id' => 11],
            ['id' => 129, 'title' => 'Karacasu', 'city_id' => 11],
            ['id' => 130, 'title' => 'Karpuzlu', 'city_id' => 11],
            ['id' => 131, 'title' => 'Koçarli', 'city_id' => 11],
            ['id' => 132, 'title' => 'Köşk', 'city_id' => 11],
            ['id' => 133, 'title' => 'Kuşadasi', 'city_id' => 11],
            ['id' => 134, 'title' => 'Kuyucak', 'city_id' => 11],
            ['id' => 135, 'title' => 'Aydin', 'city_id' => 11],
            ['id' => 136, 'title' => 'Nazilli', 'city_id' => 11],
            ['id' => 137, 'title' => 'Söke', 'city_id' => 11],
            ['id' => 138, 'title' => 'Sultanhisar', 'city_id' => 11],
            ['id' => 139, 'title' => 'Yenipazar', 'city_id' => 11],
            ['id' => 140, 'title' => 'Ayvalik', 'city_id' => 12],
            ['id' => 141, 'title' => 'Balya', 'city_id' => 12],
            ['id' => 142, 'title' => 'Bandirma', 'city_id' => 12],
            ['id' => 143, 'title' => 'Bigadiç', 'city_id' => 12],
            ['id' => 144, 'title' => 'Burhaniye', 'city_id' => 12],
            ['id' => 145, 'title' => 'Dursunbey', 'city_id' => 12],
            ['id' => 146, 'title' => 'Edremit', 'city_id' => 12],
            ['id' => 147, 'title' => 'Erdek', 'city_id' => 12],
            ['id' => 148, 'title' => 'Gömeç', 'city_id' => 12],
            ['id' => 149, 'title' => 'Gönen', 'city_id' => 12],
            ['id' => 150, 'title' => 'Havran', 'city_id' => 12],
            ['id' => 151, 'title' => 'İvrindi', 'city_id' => 12],
            ['id' => 152, 'title' => 'Kepsut', 'city_id' => 12],
            ['id' => 153, 'title' => 'Manyas', 'city_id' => 12],
            ['id' => 154, 'title' => 'Marmara', 'city_id' => 12],
            ['id' => 155, 'title' => 'Balikesir', 'city_id' => 12],
            ['id' => 156, 'title' => 'Savaştepe', 'city_id' => 12],
            ['id' => 157, 'title' => 'Sindirgi', 'city_id' => 12],
            ['id' => 158, 'title' => 'Susurluk', 'city_id' => 12],
            ['id' => 159, 'title' => 'Amasra', 'city_id' => 13],
            ['id' => 160, 'title' => 'Kurucaşile', 'city_id' => 13],
            ['id' => 161, 'title' => 'Bartin', 'city_id' => 13],
            ['id' => 162, 'title' => 'Ulus', 'city_id' => 13],
            ['id' => 163, 'title' => 'Beşiri', 'city_id' => 14],
            ['id' => 164, 'title' => 'Gercüş', 'city_id' => 14],
            ['id' => 165, 'title' => 'Hasankeyf', 'city_id' => 14],
            ['id' => 166, 'title' => 'Kozluk', 'city_id' => 14],
            ['id' => 167, 'title' => 'Batman', 'city_id' => 14],
            ['id' => 168, 'title' => 'Sason', 'city_id' => 14],
            ['id' => 169, 'title' => 'Aydintepe', 'city_id' => 15],
            ['id' => 170, 'title' => 'Demirözü', 'city_id' => 15],
            ['id' => 171, 'title' => 'Bayburt', 'city_id' => 15],
            ['id' => 172, 'title' => 'Bozüyük', 'city_id' => 16],
            ['id' => 173, 'title' => 'Gölpazari', 'city_id' => 16],
            ['id' => 174, 'title' => 'İnhisar', 'city_id' => 16],
            ['id' => 175, 'title' => 'Bilecik', 'city_id' => 16],
            ['id' => 176, 'title' => 'Osmaneli', 'city_id' => 16],
            ['id' => 177, 'title' => 'Pazaryeri', 'city_id' => 16],
            ['id' => 178, 'title' => 'Söğüt', 'city_id' => 16],
            ['id' => 179, 'title' => 'Yenipazar', 'city_id' => 16],
            ['id' => 180, 'title' => 'Adakli', 'city_id' => 17],
            ['id' => 181, 'title' => 'Genç', 'city_id' => 17],
            ['id' => 182, 'title' => 'Karliova', 'city_id' => 17],
            ['id' => 183, 'title' => 'Kiği', 'city_id' => 17],
            ['id' => 184, 'title' => 'Bingöl', 'city_id' => 17],
            ['id' => 185, 'title' => 'Solhan', 'city_id' => 17],
            ['id' => 186, 'title' => 'Yayladere', 'city_id' => 17],
            ['id' => 187, 'title' => 'Yedisu', 'city_id' => 17],
            ['id' => 188, 'title' => 'Adilcevaz', 'city_id' => 18],
            ['id' => 189, 'title' => 'Ahlat', 'city_id' => 18],
            ['id' => 190, 'title' => 'Güroymak', 'city_id' => 18],
            ['id' => 191, 'title' => 'Hizan', 'city_id' => 18],
            ['id' => 192, 'title' => 'Bitlis', 'city_id' => 18],
            ['id' => 193, 'title' => 'Mutki', 'city_id' => 18],
            ['id' => 194, 'title' => 'Tatvan', 'city_id' => 18],
            ['id' => 195, 'title' => 'Dörtdivan', 'city_id' => 19],
            ['id' => 196, 'title' => 'Gerede', 'city_id' => 19],
            ['id' => 197, 'title' => 'Göynük', 'city_id' => 19],
            ['id' => 198, 'title' => 'Kibriscik', 'city_id' => 19],
            ['id' => 199, 'title' => 'Mengen', 'city_id' => 19],
            ['id' => 200, 'title' => 'Bolu', 'city_id' => 19],
            ['id' => 201, 'title' => 'Mudurnu', 'city_id' => 19],
            ['id' => 202, 'title' => 'Seben', 'city_id' => 19],
            ['id' => 203, 'title' => 'Yeniçağa', 'city_id' => 19],
            ['id' => 204, 'title' => 'Ağlasun', 'city_id' => 20],
            ['id' => 205, 'title' => 'Altinyayla', 'city_id' => 20],
            ['id' => 206, 'title' => 'Bucak', 'city_id' => 20],
            ['id' => 207, 'title' => 'Çavdir', 'city_id' => 20],
            ['id' => 208, 'title' => 'Çeltikçi', 'city_id' => 20],
            ['id' => 209, 'title' => 'Gölhisar', 'city_id' => 20],
            ['id' => 210, 'title' => 'Karamanli', 'city_id' => 20],
            ['id' => 211, 'title' => 'Kemer', 'city_id' => 20],
            ['id' => 212, 'title' => 'Burdur', 'city_id' => 20],
            ['id' => 213, 'title' => 'Tefenni', 'city_id' => 20],
            ['id' => 214, 'title' => 'Yeşilova', 'city_id' => 20],
            ['id' => 215, 'title' => 'Büyükorhan', 'city_id' => 21],
            ['id' => 216, 'title' => 'Gemlik', 'city_id' => 21],
            ['id' => 217, 'title' => 'Gürsu', 'city_id' => 21],
            ['id' => 218, 'title' => 'Harmancik', 'city_id' => 21],
            ['id' => 219, 'title' => 'İnegöl', 'city_id' => 21],
            ['id' => 220, 'title' => 'İznik', 'city_id' => 21],
            ['id' => 221, 'title' => 'Karacabey', 'city_id' => 21],
            ['id' => 222, 'title' => 'Keles', 'city_id' => 21],
            ['id' => 223, 'title' => 'Kestel', 'city_id' => 21],
            ['id' => 224, 'title' => 'Mudanya', 'city_id' => 21],
            ['id' => 225, 'title' => 'Mustafakemalpaşa', 'city_id' => 21],
            ['id' => 226, 'title' => 'Nilüfer', 'city_id' => 21],
            ['id' => 227, 'title' => 'Orhaneli', 'city_id' => 21],
            ['id' => 228, 'title' => 'Orhangazi', 'city_id' => 21],
            ['id' => 229, 'title' => 'Osmangazi', 'city_id' => 21],
            ['id' => 230, 'title' => 'Yenişehir', 'city_id' => 21],
            ['id' => 231, 'title' => 'Yildirim', 'city_id' => 21],
            ['id' => 232, 'title' => 'Ayvacik', 'city_id' => 22],
            ['id' => 233, 'title' => 'Bayramiç', 'city_id' => 22],
            ['id' => 234, 'title' => 'Biga', 'city_id' => 22],
            ['id' => 235, 'title' => 'Bozcaada', 'city_id' => 22],
            ['id' => 236, 'title' => 'Çan', 'city_id' => 22],
            ['id' => 237, 'title' => 'Eceabat', 'city_id' => 22],
            ['id' => 238, 'title' => 'Ezine', 'city_id' => 22],
            ['id' => 239, 'title' => 'Gelibolu', 'city_id' => 22],
            ['id' => 240, 'title' => 'Gökçeada', 'city_id' => 22],
            ['id' => 241, 'title' => 'Lapseki', 'city_id' => 22],
            ['id' => 242, 'title' => 'Çanakkale', 'city_id' => 22],
            ['id' => 243, 'title' => 'Yenice', 'city_id' => 22],
            ['id' => 244, 'title' => 'Atkaracalar', 'city_id' => 23],
            ['id' => 245, 'title' => 'Bayramören', 'city_id' => 23],
            ['id' => 246, 'title' => 'Çerkeş', 'city_id' => 23],
            ['id' => 247, 'title' => 'Eldivan', 'city_id' => 23],
            ['id' => 248, 'title' => 'İlgaz', 'city_id' => 23],
            ['id' => 249, 'title' => 'Kizilirmak', 'city_id' => 23],
            ['id' => 250, 'title' => 'Korgun', 'city_id' => 23],
            ['id' => 251, 'title' => 'Kurşunlu', 'city_id' => 23],
            ['id' => 252, 'title' => 'Çankiri', 'city_id' => 23],
            ['id' => 253, 'title' => 'Orta', 'city_id' => 23],
            ['id' => 254, 'title' => 'Şabanözü', 'city_id' => 23],
            ['id' => 255, 'title' => 'Yaprakli', 'city_id' => 23],
            ['id' => 256, 'title' => 'Alaca', 'city_id' => 24],
            ['id' => 257, 'title' => 'Bayat', 'city_id' => 24],
            ['id' => 258, 'title' => 'Boğazkale', 'city_id' => 24],
            ['id' => 259, 'title' => 'Dodurga', 'city_id' => 24],
            ['id' => 260, 'title' => 'İskilip', 'city_id' => 24],
            ['id' => 261, 'title' => 'Kargi', 'city_id' => 24],
            ['id' => 262, 'title' => 'Laçin', 'city_id' => 24],
            ['id' => 263, 'title' => 'Mecitözü', 'city_id' => 24],
            ['id' => 264, 'title' => 'Oğuzlar (karaören)', 'city_id' => 24],
            ['id' => 265, 'title' => 'Ortaköy', 'city_id' => 24],
            ['id' => 266, 'title' => 'Osmancik', 'city_id' => 24],
            ['id' => 267, 'title' => 'Sungurlu', 'city_id' => 24],
            ['id' => 268, 'title' => 'Uğurludağ', 'city_id' => 24],
            ['id' => 269, 'title' => 'Acipayam', 'city_id' => 25],
            ['id' => 270, 'title' => 'Akköy', 'city_id' => 25],
            ['id' => 271, 'title' => 'Babadağ', 'city_id' => 25],
            ['id' => 272, 'title' => 'Baklan', 'city_id' => 25],
            ['id' => 273, 'title' => 'Bekilli', 'city_id' => 25],
            ['id' => 274, 'title' => 'Beyağaç', 'city_id' => 25],
            ['id' => 275, 'title' => 'Bozkurt', 'city_id' => 25],
            ['id' => 276, 'title' => 'Buldan', 'city_id' => 25],
            ['id' => 277, 'title' => 'Çal', 'city_id' => 25],
            ['id' => 278, 'title' => 'Çameli', 'city_id' => 25],
            ['id' => 279, 'title' => 'Çardak', 'city_id' => 25],
            ['id' => 280, 'title' => 'Çivril', 'city_id' => 25],
            ['id' => 281, 'title' => 'Güney', 'city_id' => 25],
            ['id' => 282, 'title' => 'Honaz', 'city_id' => 25],
            ['id' => 283, 'title' => 'Kale', 'city_id' => 25],
            ['id' => 284, 'title' => 'Denizli', 'city_id' => 25],
            ['id' => 285, 'title' => 'Sarayköy', 'city_id' => 25],
            ['id' => 286, 'title' => 'Serinhisar', 'city_id' => 25],
            ['id' => 287, 'title' => 'Tavas', 'city_id' => 25],
            ['id' => 288, 'title' => 'Bağlar', 'city_id' => 26],
            ['id' => 289, 'title' => 'Bismil', 'city_id' => 26],
            ['id' => 290, 'title' => 'Çermik', 'city_id' => 26],
            ['id' => 291, 'title' => 'Çinar', 'city_id' => 26],
            ['id' => 292, 'title' => 'Çüngüş', 'city_id' => 26],
            ['id' => 293, 'title' => 'Dicle', 'city_id' => 26],
            ['id' => 294, 'title' => 'Eğil', 'city_id' => 26],
            ['id' => 295, 'title' => 'Ergani', 'city_id' => 26],
            ['id' => 296, 'title' => 'Hani', 'city_id' => 26],
            ['id' => 297, 'title' => 'Hazro', 'city_id' => 26],
            ['id' => 298, 'title' => 'Kayapinar', 'city_id' => 26],
            ['id' => 299, 'title' => 'Kocaköy', 'city_id' => 26],
            ['id' => 300, 'title' => 'Kulp', 'city_id' => 26],
            ['id' => 301, 'title' => 'Lice', 'city_id' => 26],
            ['id' => 302, 'title' => 'Silvan', 'city_id' => 26],
            ['id' => 303, 'title' => 'Sur', 'city_id' => 26],
            ['id' => 304, 'title' => 'Yenişehir', 'city_id' => 26],
            ['id' => 305, 'title' => 'Akçakoca', 'city_id' => 27],
            ['id' => 306, 'title' => 'Çilimli', 'city_id' => 27],
            ['id' => 307, 'title' => 'Cumayeri', 'city_id' => 27],
            ['id' => 308, 'title' => 'Gölyaka', 'city_id' => 27],
            ['id' => 309, 'title' => 'Gümüşova', 'city_id' => 27],
            ['id' => 310, 'title' => 'Kaynaşli', 'city_id' => 27],
            ['id' => 311, 'title' => 'Düzce', 'city_id' => 27],
            ['id' => 312, 'title' => 'Yiğilca', 'city_id' => 27],
            ['id' => 313, 'title' => 'Enez', 'city_id' => 28],
            ['id' => 314, 'title' => 'Havsa', 'city_id' => 28],
            ['id' => 315, 'title' => 'İpsala', 'city_id' => 28],
            ['id' => 316, 'title' => 'Keşan', 'city_id' => 28],
            ['id' => 317, 'title' => 'Lalapaşa', 'city_id' => 28],
            ['id' => 318, 'title' => 'Meriç', 'city_id' => 28],
            ['id' => 319, 'title' => 'Edirne', 'city_id' => 28],
            ['id' => 320, 'title' => 'Süloğlu', 'city_id' => 28],
            ['id' => 321, 'title' => 'Uzunköprü', 'city_id' => 28],
            ['id' => 322, 'title' => 'Ağin', 'city_id' => 29],
            ['id' => 323, 'title' => 'Alacakaya', 'city_id' => 29],
            ['id' => 324, 'title' => 'Aricak', 'city_id' => 29],
            ['id' => 325, 'title' => 'Baskil', 'city_id' => 29],
            ['id' => 326, 'title' => 'Karakoçan', 'city_id' => 29],
            ['id' => 327, 'title' => 'Keban', 'city_id' => 29],
            ['id' => 328, 'title' => 'Kovancilar', 'city_id' => 29],
            ['id' => 329, 'title' => 'Maden', 'city_id' => 29],
            ['id' => 330, 'title' => 'Elaziğ', 'city_id' => 29],
            ['id' => 331, 'title' => 'Palu', 'city_id' => 29],
            ['id' => 332, 'title' => 'Sivrice', 'city_id' => 29],
            ['id' => 333, 'title' => 'Çayirli', 'city_id' => 30],
            ['id' => 334, 'title' => 'İliç', 'city_id' => 30],
            ['id' => 335, 'title' => 'Kemah', 'city_id' => 30],
            ['id' => 336, 'title' => 'Kemaliye', 'city_id' => 30],
            ['id' => 337, 'title' => 'Erzincan', 'city_id' => 30],
            ['id' => 338, 'title' => 'Otlukbeli', 'city_id' => 30],
            ['id' => 339, 'title' => 'Refahiye', 'city_id' => 30],
            ['id' => 340, 'title' => 'Tercan', 'city_id' => 30],
            ['id' => 341, 'title' => 'Üzümlü', 'city_id' => 30],
            ['id' => 342, 'title' => 'Aşkale', 'city_id' => 31],
            ['id' => 343, 'title' => 'Aziziye', 'city_id' => 31],
            ['id' => 344, 'title' => 'Çat', 'city_id' => 31],
            ['id' => 345, 'title' => 'Hinis', 'city_id' => 31],
            ['id' => 346, 'title' => 'Horasan', 'city_id' => 31],
            ['id' => 347, 'title' => 'İspir', 'city_id' => 31],
            ['id' => 348, 'title' => 'Karaçoban', 'city_id' => 31],
            ['id' => 349, 'title' => 'Karayazi', 'city_id' => 31],
            ['id' => 350, 'title' => 'Köprüköy', 'city_id' => 31],
            ['id' => 351, 'title' => 'Narman', 'city_id' => 31],
            ['id' => 352, 'title' => 'Oltu', 'city_id' => 31],
            ['id' => 353, 'title' => 'Olur', 'city_id' => 31],
            ['id' => 354, 'title' => 'Palandöken', 'city_id' => 31],
            ['id' => 355, 'title' => 'Pasinler', 'city_id' => 31],
            ['id' => 356, 'title' => 'Pazaryolu', 'city_id' => 31],
            ['id' => 357, 'title' => 'Şenkaya', 'city_id' => 31],
            ['id' => 358, 'title' => 'Tekman', 'city_id' => 31],
            ['id' => 359, 'title' => 'Tortum', 'city_id' => 31],
            ['id' => 360, 'title' => 'Uzundere', 'city_id' => 31],
            ['id' => 361, 'title' => 'Yakutiye', 'city_id' => 31],
            ['id' => 362, 'title' => 'Alpu', 'city_id' => 32],
            ['id' => 363, 'title' => 'Beylikova', 'city_id' => 32],
            ['id' => 364, 'title' => 'Çifteler', 'city_id' => 32],
            ['id' => 365, 'title' => 'Günyüzü', 'city_id' => 32],
            ['id' => 366, 'title' => 'Han', 'city_id' => 32],
            ['id' => 367, 'title' => 'İnönü', 'city_id' => 32],
            ['id' => 368, 'title' => 'Mahmudiye', 'city_id' => 32],
            ['id' => 369, 'title' => 'Mihalgazi', 'city_id' => 32],
            ['id' => 370, 'title' => 'Mihaliçcik', 'city_id' => 32],
            ['id' => 371, 'title' => 'Odunpazari', 'city_id' => 32],
            ['id' => 372, 'title' => 'Saricakaya', 'city_id' => 32],
            ['id' => 373, 'title' => 'Seyitgazi', 'city_id' => 32],
            ['id' => 374, 'title' => 'Sivrihisar', 'city_id' => 32],
            ['id' => 375, 'title' => 'Tepebaşi', 'city_id' => 32],
            ['id' => 376, 'title' => 'Araban', 'city_id' => 33],
            ['id' => 377, 'title' => 'İslahiye', 'city_id' => 33],
            ['id' => 378, 'title' => 'Karkamiş', 'city_id' => 33],
            ['id' => 379, 'title' => 'Nizip', 'city_id' => 33],
            ['id' => 380, 'title' => 'Nurdaği', 'city_id' => 33],
            ['id' => 381, 'title' => 'Oğuzeli', 'city_id' => 33],
            ['id' => 382, 'title' => 'Şahinbey', 'city_id' => 33],
            ['id' => 383, 'title' => 'Şehitkamil', 'city_id' => 33],
            ['id' => 384, 'title' => 'Yavuzeli', 'city_id' => 33],
            ['id' => 385, 'title' => 'Alucra', 'city_id' => 34],
            ['id' => 386, 'title' => 'Bulancak', 'city_id' => 34],
            ['id' => 387, 'title' => 'Çamoluk', 'city_id' => 34],
            ['id' => 388, 'title' => 'Çanakçi', 'city_id' => 34],
            ['id' => 389, 'title' => 'Dereli', 'city_id' => 34],
            ['id' => 390, 'title' => 'Doğankent', 'city_id' => 34],
            ['id' => 391, 'title' => 'Espiye', 'city_id' => 34],
            ['id' => 392, 'title' => 'Eynesil', 'city_id' => 34],
            ['id' => 393, 'title' => 'Giresun', 'city_id' => 34],
            ['id' => 394, 'title' => 'Görele', 'city_id' => 34],
            ['id' => 395, 'title' => 'Güce', 'city_id' => 34],
            ['id' => 396, 'title' => 'Keşap', 'city_id' => 34],
            ['id' => 397, 'title' => 'Piraziz', 'city_id' => 34],
            ['id' => 398, 'title' => 'Şebinkarahisar', 'city_id' => 34],
            ['id' => 399, 'title' => 'Tirebolu', 'city_id' => 34],
            ['id' => 400, 'title' => 'Yağlidere', 'city_id' => 34],
            ['id' => 401, 'title' => 'Kelkit', 'city_id' => 35],
            ['id' => 402, 'title' => 'Köse', 'city_id' => 35],
            ['id' => 403, 'title' => 'Kürtün', 'city_id' => 35],
            ['id' => 404, 'title' => 'Gümüşhane', 'city_id' => 35],
            ['id' => 405, 'title' => 'Şiran', 'city_id' => 35],
            ['id' => 406, 'title' => 'Torul', 'city_id' => 35],
            ['id' => 407, 'title' => 'Çukurca', 'city_id' => 36],
            ['id' => 408, 'title' => 'Hakkari', 'city_id' => 36],
            ['id' => 409, 'title' => 'Şemdinli', 'city_id' => 36],
            ['id' => 410, 'title' => 'Yüksekova', 'city_id' => 36],
            ['id' => 411, 'title' => 'Altinözü', 'city_id' => 37],
            ['id' => 412, 'title' => 'Antakya', 'city_id' => 37],
            ['id' => 413, 'title' => 'Belen', 'city_id' => 37],
            ['id' => 414, 'title' => 'Dörtyol', 'city_id' => 37],
            ['id' => 415, 'title' => 'Erzin', 'city_id' => 37],
            ['id' => 416, 'title' => 'Hassa', 'city_id' => 37],
            ['id' => 417, 'title' => 'İskenderun', 'city_id' => 37],
            ['id' => 418, 'title' => 'Kirikhan', 'city_id' => 37],
            ['id' => 419, 'title' => 'Kumlu', 'city_id' => 37],
            ['id' => 420, 'title' => 'Reyhanli', 'city_id' => 37],
            ['id' => 421, 'title' => 'Samandağ', 'city_id' => 37],
            ['id' => 422, 'title' => 'Yayladaği', 'city_id' => 37],
            ['id' => 423, 'title' => 'Aralik', 'city_id' => 38],
            ['id' => 424, 'title' => 'Karakoyunlu', 'city_id' => 38],
            ['id' => 425, 'title' => 'İğdir', 'city_id' => 38],
            ['id' => 426, 'title' => 'Tuzluca', 'city_id' => 38],
            ['id' => 427, 'title' => 'Aksu', 'city_id' => 39],
            ['id' => 428, 'title' => 'Atabey', 'city_id' => 39],
            ['id' => 429, 'title' => 'Eğridir', 'city_id' => 39],
            ['id' => 430, 'title' => 'Gelendost', 'city_id' => 39],
            ['id' => 431, 'title' => 'Gönen', 'city_id' => 39],
            ['id' => 432, 'title' => 'Keçiborlu', 'city_id' => 39],
            ['id' => 433, 'title' => 'İsparta', 'city_id' => 39],
            ['id' => 434, 'title' => 'Şarkikaraağaç', 'city_id' => 39],
            ['id' => 435, 'title' => 'Senirkent', 'city_id' => 39],
            ['id' => 436, 'title' => 'Sütçüler', 'city_id' => 39],
            ['id' => 437, 'title' => 'Uluborlu', 'city_id' => 39],
            ['id' => 438, 'title' => 'Yalvaç', 'city_id' => 39],
            ['id' => 439, 'title' => 'Yenişarbademli', 'city_id' => 39],
            ['id' => 440, 'title' => 'Adalar', 'city_id' => 40],
            ['id' => 441, 'title' => 'Arnavutköy', 'city_id' => 40],
            ['id' => 442, 'title' => 'Ataşehir', 'city_id' => 40],
            ['id' => 443, 'title' => 'Avcilar', 'city_id' => 40],
            ['id' => 444, 'title' => 'Bağcilar', 'city_id' => 40],
            ['id' => 445, 'title' => 'Bahçelievler', 'city_id' => 40],
            ['id' => 446, 'title' => 'Bakirköy', 'city_id' => 40],
            ['id' => 447, 'title' => 'Başakşehir', 'city_id' => 40],
            ['id' => 448, 'title' => 'Bayrampaşa', 'city_id' => 40],
            ['id' => 449, 'title' => 'Beşiktaş', 'city_id' => 40],
            ['id' => 450, 'title' => 'Beykoz', 'city_id' => 40],
            ['id' => 451, 'title' => 'Beylikdüzü', 'city_id' => 40],
            ['id' => 452, 'title' => 'Beyoğlu', 'city_id' => 40],
            ['id' => 453, 'title' => 'Büyükçekmece', 'city_id' => 40],
            ['id' => 454, 'title' => 'Çatalca', 'city_id' => 40],
            ['id' => 455, 'title' => 'Çekmeköy', 'city_id' => 40],
            ['id' => 456, 'title' => 'Esenler', 'city_id' => 40],
            ['id' => 457, 'title' => 'Esenyurt', 'city_id' => 40],
            ['id' => 458, 'title' => 'Eyüp', 'city_id' => 40],
            ['id' => 459, 'title' => 'Fatih', 'city_id' => 40],
            ['id' => 460, 'title' => 'Gaziosmanpaşa', 'city_id' => 40],
            ['id' => 461, 'title' => 'Güngören', 'city_id' => 40],
            ['id' => 462, 'title' => 'Kadiköy', 'city_id' => 40],
            ['id' => 463, 'title' => 'Kağithane', 'city_id' => 40],
            ['id' => 464, 'title' => 'Kartal', 'city_id' => 40],
            ['id' => 465, 'title' => 'Küçükçekmece', 'city_id' => 40],
            ['id' => 466, 'title' => 'Maltepe', 'city_id' => 40],
            ['id' => 467, 'title' => 'Pendik', 'city_id' => 40],
            ['id' => 468, 'title' => 'Sancaktepe', 'city_id' => 40],
            ['id' => 469, 'title' => 'Sariyer', 'city_id' => 40],
            ['id' => 470, 'title' => 'Şile', 'city_id' => 40],
            ['id' => 471, 'title' => 'Silivri', 'city_id' => 40],
            ['id' => 472, 'title' => 'Şişli', 'city_id' => 40],
            ['id' => 473, 'title' => 'Sultanbeyli', 'city_id' => 40],
            ['id' => 474, 'title' => 'Sultangazi', 'city_id' => 40],
            ['id' => 475, 'title' => 'Tuzla', 'city_id' => 40],
            ['id' => 476, 'title' => 'Ümraniye', 'city_id' => 40],
            ['id' => 477, 'title' => 'Üsküdar', 'city_id' => 40],
            ['id' => 478, 'title' => 'Zeytinburnu', 'city_id' => 40],
            ['id' => 479, 'title' => 'Aliağa', 'city_id' => 41],
            ['id' => 480, 'title' => 'Balçova', 'city_id' => 41],
            ['id' => 481, 'title' => 'Bayindir', 'city_id' => 41],
            ['id' => 482, 'title' => 'Bayrakli', 'city_id' => 41],
            ['id' => 483, 'title' => 'Bergama', 'city_id' => 41],
            ['id' => 484, 'title' => 'Beydağ', 'city_id' => 41],
            ['id' => 485, 'title' => 'Bornova', 'city_id' => 41],
            ['id' => 486, 'title' => 'Buca', 'city_id' => 41],
            ['id' => 487, 'title' => 'Çeşme', 'city_id' => 41],
            ['id' => 488, 'title' => 'Çiğli', 'city_id' => 41],
            ['id' => 489, 'title' => 'Dikili', 'city_id' => 41],
            ['id' => 490, 'title' => 'Foça', 'city_id' => 41],
            ['id' => 491, 'title' => 'Gaziemir', 'city_id' => 41],
            ['id' => 492, 'title' => 'Güzelbahçe', 'city_id' => 41],
            ['id' => 493, 'title' => 'Karabağlar', 'city_id' => 41],
            ['id' => 494, 'title' => 'Karaburun', 'city_id' => 41],
            ['id' => 495, 'title' => 'Karşiyaka', 'city_id' => 41],
            ['id' => 496, 'title' => 'Kemalpaşa', 'city_id' => 41],
            ['id' => 497, 'title' => 'Kinik', 'city_id' => 41],
            ['id' => 498, 'title' => 'Kiraz', 'city_id' => 41],
            ['id' => 499, 'title' => 'Konak', 'city_id' => 41],
            ['id' => 500, 'title' => 'Menderes', 'city_id' => 41],
            ['id' => 501, 'title' => 'Menemen', 'city_id' => 41],
            ['id' => 502, 'title' => 'Nerlidere', 'city_id' => 41],
            ['id' => 503, 'title' => 'Ödemiş', 'city_id' => 41],
            ['id' => 504, 'title' => 'Seferhisar', 'city_id' => 41],
            ['id' => 505, 'title' => 'Selçuk', 'city_id' => 41],
            ['id' => 506, 'title' => 'Tire', 'city_id' => 41],
            ['id' => 507, 'title' => 'Torbali', 'city_id' => 41],
            ['id' => 508, 'title' => 'Urla', 'city_id' => 41],
            ['id' => 509, 'title' => 'Afşin', 'city_id' => 42],
            ['id' => 510, 'title' => 'Andirin', 'city_id' => 42],
            ['id' => 511, 'title' => 'Çağlayancerit', 'city_id' => 42],
            ['id' => 512, 'title' => 'Ekinözü', 'city_id' => 42],
            ['id' => 513, 'title' => 'Elbistan', 'city_id' => 42],
            ['id' => 514, 'title' => 'Göksun', 'city_id' => 42],
            ['id' => 515, 'title' => 'Kahramanmaraş', 'city_id' => 42],
            ['id' => 516, 'title' => 'Nurhak', 'city_id' => 42],
            ['id' => 517, 'title' => 'Pazarcik', 'city_id' => 42],
            ['id' => 518, 'title' => 'Türkoğlu', 'city_id' => 42],
            ['id' => 519, 'title' => 'Eflani', 'city_id' => 43],
            ['id' => 520, 'title' => 'Eskipazar', 'city_id' => 43],
            ['id' => 521, 'title' => 'Karabük', 'city_id' => 43],
            ['id' => 522, 'title' => 'Ovacik', 'city_id' => 43],
            ['id' => 523, 'title' => 'Safranbolu', 'city_id' => 43],
            ['id' => 524, 'title' => 'Yenice', 'city_id' => 43],
            ['id' => 525, 'title' => 'Ayranci', 'city_id' => 44],
            ['id' => 526, 'title' => 'Başyayla', 'city_id' => 44],
            ['id' => 527, 'title' => 'Ermenek', 'city_id' => 44],
            ['id' => 528, 'title' => 'Kazimkarabekir', 'city_id' => 44],
            ['id' => 529, 'title' => 'Karaman', 'city_id' => 44],
            ['id' => 530, 'title' => 'Sariveliler', 'city_id' => 44],
            ['id' => 531, 'title' => 'Akyaka', 'city_id' => 45],
            ['id' => 532, 'title' => 'Arpaçay', 'city_id' => 45],
            ['id' => 533, 'title' => 'Digor', 'city_id' => 45],
            ['id' => 534, 'title' => 'Kağizman', 'city_id' => 45],
            ['id' => 535, 'title' => 'Kars', 'city_id' => 45],
            ['id' => 536, 'title' => 'Sarikamiş', 'city_id' => 45],
            ['id' => 537, 'title' => 'Selim', 'city_id' => 45],
            ['id' => 538, 'title' => 'Susuz', 'city_id' => 45],
            ['id' => 539, 'title' => 'Abana', 'city_id' => 46],
            ['id' => 540, 'title' => 'Ağli', 'city_id' => 46],
            ['id' => 541, 'title' => 'Araç', 'city_id' => 46],
            ['id' => 542, 'title' => 'Azdavay', 'city_id' => 46],
            ['id' => 543, 'title' => 'Bozkurt', 'city_id' => 46],
            ['id' => 544, 'title' => 'Çatalzeytin', 'city_id' => 46],
            ['id' => 545, 'title' => 'Cide', 'city_id' => 46],
            ['id' => 546, 'title' => 'Daday', 'city_id' => 46],
            ['id' => 547, 'title' => 'Devrekani', 'city_id' => 46],
            ['id' => 548, 'title' => 'Doğanyurt', 'city_id' => 46],
            ['id' => 549, 'title' => 'Hanönü', 'city_id' => 46],
            ['id' => 550, 'title' => 'İhsangazi', 'city_id' => 46],
            ['id' => 551, 'title' => 'İnebolu', 'city_id' => 46],
            ['id' => 552, 'title' => 'Küre', 'city_id' => 46],
            ['id' => 553, 'title' => 'Kastamonu', 'city_id' => 46],
            ['id' => 554, 'title' => 'Pinarbaşi', 'city_id' => 46],
            ['id' => 555, 'title' => 'Şenpazar', 'city_id' => 46],
            ['id' => 556, 'title' => 'Seydiler', 'city_id' => 46],
            ['id' => 557, 'title' => 'Taşköprü', 'city_id' => 46],
            ['id' => 558, 'title' => 'Tosya', 'city_id' => 46],
            ['id' => 559, 'title' => 'Akkişla', 'city_id' => 47],
            ['id' => 560, 'title' => 'Bünyan', 'city_id' => 47],
            ['id' => 561, 'title' => 'Develi', 'city_id' => 47],
            ['id' => 562, 'title' => 'Felahiye', 'city_id' => 47],
            ['id' => 563, 'title' => 'Hacilar', 'city_id' => 47],
            ['id' => 564, 'title' => 'İncesu', 'city_id' => 47],
            ['id' => 565, 'title' => 'Kocasinan', 'city_id' => 47],
            ['id' => 566, 'title' => 'Melikgazi', 'city_id' => 47],
            ['id' => 567, 'title' => 'Özvatan', 'city_id' => 47],
            ['id' => 568, 'title' => 'Pinarbaşi', 'city_id' => 47],
            ['id' => 569, 'title' => 'Sarioğlan', 'city_id' => 47],
            ['id' => 570, 'title' => 'Sariz', 'city_id' => 47],
            ['id' => 571, 'title' => 'Talas', 'city_id' => 47],
            ['id' => 572, 'title' => 'Tomarza', 'city_id' => 47],
            ['id' => 573, 'title' => 'Yahyali', 'city_id' => 47],
            ['id' => 574, 'title' => 'Yeşilhisar', 'city_id' => 47],
            ['id' => 575, 'title' => 'Elbeyli', 'city_id' => 48],
            ['id' => 576, 'title' => 'Kilis', 'city_id' => 48],
            ['id' => 577, 'title' => 'Musabeyli', 'city_id' => 48],
            ['id' => 578, 'title' => 'Polateli', 'city_id' => 48],
            ['id' => 579, 'title' => 'Bahşili', 'city_id' => 49],
            ['id' => 580, 'title' => 'Balişeyh', 'city_id' => 49],
            ['id' => 581, 'title' => 'Çelebi', 'city_id' => 49],
            ['id' => 582, 'title' => 'Delice', 'city_id' => 49],
            ['id' => 583, 'title' => 'Karakeçili', 'city_id' => 49],
            ['id' => 584, 'title' => 'Keskin', 'city_id' => 49],
            ['id' => 585, 'title' => 'Kirikkale', 'city_id' => 49],
            ['id' => 586, 'title' => 'Sulakyurt', 'city_id' => 49],
            ['id' => 587, 'title' => 'Yahşihan', 'city_id' => 49],
            ['id' => 588, 'title' => 'Babaeski', 'city_id' => 50],
            ['id' => 589, 'title' => 'Demirköy', 'city_id' => 50],
            ['id' => 590, 'title' => 'Kofçaz', 'city_id' => 50],
            ['id' => 591, 'title' => 'Lüleburgaz', 'city_id' => 50],
            ['id' => 592, 'title' => 'Kirklareli', 'city_id' => 50],
            ['id' => 593, 'title' => 'Pehlivanköy', 'city_id' => 50],
            ['id' => 594, 'title' => 'Pinarhisar', 'city_id' => 50],
            ['id' => 595, 'title' => 'Vize', 'city_id' => 50],
            ['id' => 596, 'title' => 'Akçakent', 'city_id' => 51],
            ['id' => 597, 'title' => 'Akpinar', 'city_id' => 51],
            ['id' => 598, 'title' => 'Boztepe', 'city_id' => 51],
            ['id' => 599, 'title' => 'Çiçekdaği', 'city_id' => 51],
            ['id' => 600, 'title' => 'Kaman', 'city_id' => 51],
            ['id' => 601, 'title' => 'Kirşehir', 'city_id' => 51],
            ['id' => 602, 'title' => 'Mucur', 'city_id' => 51],
            ['id' => 603, 'title' => 'Başiskele', 'city_id' => 52],
            ['id' => 604, 'title' => 'Çayirova', 'city_id' => 52],
            ['id' => 605, 'title' => 'Darica', 'city_id' => 52],
            ['id' => 606, 'title' => 'Derince', 'city_id' => 52],
            ['id' => 607, 'title' => 'Dilovasi', 'city_id' => 52],
            ['id' => 608, 'title' => 'Gebze', 'city_id' => 52],
            ['id' => 609, 'title' => 'Gölcük', 'city_id' => 52],
            ['id' => 610, 'title' => 'İzmit', 'city_id' => 52],
            ['id' => 611, 'title' => 'Kandira', 'city_id' => 52],
            ['id' => 612, 'title' => 'Karamürsel', 'city_id' => 52],
            ['id' => 613, 'title' => 'Kartepe', 'city_id' => 52],
            ['id' => 614, 'title' => 'Körfez', 'city_id' => 52],
            ['id' => 615, 'title' => 'Ahirli', 'city_id' => 53],
            ['id' => 616, 'title' => 'Akören', 'city_id' => 53],
            ['id' => 617, 'title' => 'Akşehir', 'city_id' => 53],
            ['id' => 618, 'title' => 'Altinekin', 'city_id' => 53],
            ['id' => 619, 'title' => 'Beyşehir', 'city_id' => 53],
            ['id' => 620, 'title' => 'Bozkir', 'city_id' => 53],
            ['id' => 621, 'title' => 'Çeltik', 'city_id' => 53],
            ['id' => 622, 'title' => 'Cihanbeyli', 'city_id' => 53],
            ['id' => 623, 'title' => 'Çumra', 'city_id' => 53],
            ['id' => 624, 'title' => 'Derbent', 'city_id' => 53],
            ['id' => 625, 'title' => 'Derebucak', 'city_id' => 53],
            ['id' => 626, 'title' => 'Doğanhisar', 'city_id' => 53],
            ['id' => 627, 'title' => 'Emirgazi', 'city_id' => 53],
            ['id' => 628, 'title' => 'Ereğli', 'city_id' => 53],
            ['id' => 629, 'title' => 'Güneysinir', 'city_id' => 53],
            ['id' => 630, 'title' => 'Hadim', 'city_id' => 53],
            ['id' => 631, 'title' => 'Halkapinar', 'city_id' => 53],
            ['id' => 632, 'title' => 'Hüyük', 'city_id' => 53],
            ['id' => 633, 'title' => 'İlgin', 'city_id' => 53],
            ['id' => 634, 'title' => 'Kadinhani', 'city_id' => 53],
            ['id' => 635, 'title' => 'Karapinar', 'city_id' => 53],
            ['id' => 636, 'title' => 'Karatay', 'city_id' => 53],
            ['id' => 637, 'title' => 'Kulu', 'city_id' => 53],
            ['id' => 638, 'title' => 'Meram', 'city_id' => 53],
            ['id' => 639, 'title' => 'Sarayönü', 'city_id' => 53],
            ['id' => 640, 'title' => 'Selçuklu', 'city_id' => 53],
            ['id' => 641, 'title' => 'Seydişehir', 'city_id' => 53],
            ['id' => 642, 'title' => 'Taşkent', 'city_id' => 53],
            ['id' => 643, 'title' => 'Tuzlukçu', 'city_id' => 53],
            ['id' => 644, 'title' => 'Yalihüyük', 'city_id' => 53],
            ['id' => 645, 'title' => 'Yunak', 'city_id' => 53],
            ['id' => 646, 'title' => 'Altintaş', 'city_id' => 54],
            ['id' => 647, 'title' => 'Aslanapa', 'city_id' => 54],
            ['id' => 648, 'title' => 'Çavdarhisar', 'city_id' => 54],
            ['id' => 649, 'title' => 'Domaniç', 'city_id' => 54],
            ['id' => 650, 'title' => 'Dumlupinar', 'city_id' => 54],
            ['id' => 651, 'title' => 'Emet', 'city_id' => 54],
            ['id' => 652, 'title' => 'Gediz', 'city_id' => 54],
            ['id' => 653, 'title' => 'Hisarcik', 'city_id' => 54],
            ['id' => 654, 'title' => 'Kütahya', 'city_id' => 54],
            ['id' => 655, 'title' => 'Pazarlar', 'city_id' => 54],
            ['id' => 656, 'title' => 'Şaphane', 'city_id' => 54],
            ['id' => 657, 'title' => 'Simav', 'city_id' => 54],
            ['id' => 658, 'title' => 'Tavşanli', 'city_id' => 54],
            ['id' => 659, 'title' => 'Akçadağ', 'city_id' => 55],
            ['id' => 660, 'title' => 'Arapkir', 'city_id' => 55],
            ['id' => 661, 'title' => 'Arguvan', 'city_id' => 55],
            ['id' => 662, 'title' => 'Battalgazi', 'city_id' => 55],
            ['id' => 663, 'title' => 'Darende', 'city_id' => 55],
            ['id' => 664, 'title' => 'Doğanşehir', 'city_id' => 55],
            ['id' => 665, 'title' => 'Doğanyol', 'city_id' => 55],
            ['id' => 666, 'title' => 'Hekimhan', 'city_id' => 55],
            ['id' => 667, 'title' => 'Kale', 'city_id' => 55],
            ['id' => 668, 'title' => 'Kuluncak', 'city_id' => 55],
            ['id' => 669, 'title' => 'Malatya', 'city_id' => 55],
            ['id' => 670, 'title' => 'Pötürge', 'city_id' => 55],
            ['id' => 671, 'title' => 'Yazihan', 'city_id' => 55],
            ['id' => 672, 'title' => 'Yeşilyurt', 'city_id' => 55],
            ['id' => 673, 'title' => 'Ahmetli', 'city_id' => 56],
            ['id' => 674, 'title' => 'Akhisar', 'city_id' => 56],
            ['id' => 675, 'title' => 'Alaşehir', 'city_id' => 56],
            ['id' => 676, 'title' => 'Demirci', 'city_id' => 56],
            ['id' => 677, 'title' => 'Gölmarmara', 'city_id' => 56],
            ['id' => 678, 'title' => 'Gördes', 'city_id' => 56],
            ['id' => 679, 'title' => 'Kirkağaç', 'city_id' => 56],
            ['id' => 680, 'title' => 'Köprübaşi', 'city_id' => 56],
            ['id' => 681, 'title' => 'Kula', 'city_id' => 56],
            ['id' => 682, 'title' => 'Manisa', 'city_id' => 56],
            ['id' => 683, 'title' => 'Salihli', 'city_id' => 56],
            ['id' => 684, 'title' => 'Sarigöl', 'city_id' => 56],
            ['id' => 685, 'title' => 'Saruhanli', 'city_id' => 56],
            ['id' => 686, 'title' => 'Selendi', 'city_id' => 56],
            ['id' => 687, 'title' => 'Soma', 'city_id' => 56],
            ['id' => 688, 'title' => 'Turgutlu', 'city_id' => 56],
            ['id' => 689, 'title' => 'Dargeçit', 'city_id' => 57],
            ['id' => 690, 'title' => 'Derik', 'city_id' => 57],
            ['id' => 691, 'title' => 'Kiziltepe', 'city_id' => 57],
            ['id' => 692, 'title' => 'Mazidaği', 'city_id' => 57],
            ['id' => 693, 'title' => 'Mardin', 'city_id' => 57],
            ['id' => 694, 'title' => 'Midyat', 'city_id' => 57],
            ['id' => 695, 'title' => 'Nusaybin', 'city_id' => 57],
            ['id' => 696, 'title' => 'Ömerli', 'city_id' => 57],
            ['id' => 697, 'title' => 'Savur', 'city_id' => 57],
            ['id' => 698, 'title' => 'Yeşilli', 'city_id' => 57],
            ['id' => 699, 'title' => 'Akdeniz', 'city_id' => 58],
            ['id' => 700, 'title' => 'Anamur', 'city_id' => 58],
            ['id' => 701, 'title' => 'Aydincik', 'city_id' => 58],
            ['id' => 702, 'title' => 'Bozyazi', 'city_id' => 58],
            ['id' => 703, 'title' => 'Çamliyayla', 'city_id' => 58],
            ['id' => 704, 'title' => 'Erdemli', 'city_id' => 58],
            ['id' => 705, 'title' => 'Gülnar', 'city_id' => 58],
            ['id' => 706, 'title' => 'Mezitli', 'city_id' => 58],
            ['id' => 707, 'title' => 'Mut', 'city_id' => 58],
            ['id' => 708, 'title' => 'Silifke', 'city_id' => 58],
            ['id' => 709, 'title' => 'Tarsus', 'city_id' => 58],
            ['id' => 710, 'title' => 'Toroslar', 'city_id' => 58],
            ['id' => 711, 'title' => 'Yenişehir', 'city_id' => 58],
            ['id' => 712, 'title' => 'Bodrum', 'city_id' => 59],
            ['id' => 713, 'title' => 'Dalaman', 'city_id' => 59],
            ['id' => 714, 'title' => 'Datça', 'city_id' => 59],
            ['id' => 715, 'title' => 'Fethiye', 'city_id' => 59],
            ['id' => 716, 'title' => 'Güllük', 'city_id' => 59],
            ['id' => 717, 'title' => 'Kavaklidere', 'city_id' => 59],
            ['id' => 718, 'title' => 'Köyceğiz', 'city_id' => 59],
            ['id' => 719, 'title' => 'Marmaris', 'city_id' => 59],
            ['id' => 720, 'title' => 'Muğla', 'city_id' => 59],
            ['id' => 721, 'title' => 'Milas', 'city_id' => 59],
            ['id' => 722, 'title' => 'Ortaca', 'city_id' => 59],
            ['id' => 723, 'title' => 'Ula', 'city_id' => 59],
            ['id' => 724, 'title' => 'Yatağan', 'city_id' => 59],
            ['id' => 725, 'title' => 'Bulanik', 'city_id' => 60],
            ['id' => 726, 'title' => 'Hasköy', 'city_id' => 60],
            ['id' => 727, 'title' => 'Korkut', 'city_id' => 60],
            ['id' => 728, 'title' => 'Malazgirt', 'city_id' => 60],
            ['id' => 729, 'title' => 'Muş', 'city_id' => 60],
            ['id' => 730, 'title' => 'Varto', 'city_id' => 60],
            ['id' => 731, 'title' => 'Acigöl', 'city_id' => 61],
            ['id' => 732, 'title' => 'Avanos', 'city_id' => 61],
            ['id' => 733, 'title' => 'Derinkuyu', 'city_id' => 61],
            ['id' => 734, 'title' => 'Gülşehir', 'city_id' => 61],
            ['id' => 735, 'title' => 'Hacibektaş', 'city_id' => 61],
            ['id' => 736, 'title' => 'Kozakli', 'city_id' => 61],
            ['id' => 737, 'title' => 'Nevşehir', 'city_id' => 61],
            ['id' => 738, 'title' => 'Ürgüp', 'city_id' => 61],
            ['id' => 739, 'title' => 'Altunhisar', 'city_id' => 62],
            ['id' => 740, 'title' => 'Bor', 'city_id' => 62],
            ['id' => 741, 'title' => 'Çamardi', 'city_id' => 62],
            ['id' => 742, 'title' => 'Çiftlik (özyurt)', 'city_id' => 62],
            ['id' => 743, 'title' => 'Niğde', 'city_id' => 62],
            ['id' => 744, 'title' => 'Ulukişla', 'city_id' => 62],
            ['id' => 745, 'title' => 'Akkuş', 'city_id' => 63],
            ['id' => 746, 'title' => 'Aybasti', 'city_id' => 63],
            ['id' => 747, 'title' => 'Çamaş', 'city_id' => 63],
            ['id' => 748, 'title' => 'Çatalpinar', 'city_id' => 63],
            ['id' => 749, 'title' => 'Çaybaşi', 'city_id' => 63],
            ['id' => 750, 'title' => 'Fatsa', 'city_id' => 63],
            ['id' => 751, 'title' => 'Gölköy', 'city_id' => 63],
            ['id' => 752, 'title' => 'Gülyali', 'city_id' => 63],
            ['id' => 753, 'title' => 'Gürgentepe', 'city_id' => 63],
            ['id' => 754, 'title' => 'İkizce', 'city_id' => 63],
            ['id' => 755, 'title' => 'Kabataş', 'city_id' => 63],
            ['id' => 756, 'title' => 'Kabadüz', 'city_id' => 63],
            ['id' => 757, 'title' => 'Korgan', 'city_id' => 63],
            ['id' => 758, 'title' => 'Kumru', 'city_id' => 63],
            ['id' => 759, 'title' => 'Ordu', 'city_id' => 63],
            ['id' => 760, 'title' => 'Mesudiye', 'city_id' => 63],
            ['id' => 761, 'title' => 'Perşembe', 'city_id' => 63],
            ['id' => 762, 'title' => 'Ulubey', 'city_id' => 63],
            ['id' => 763, 'title' => 'Ünye', 'city_id' => 63],
            ['id' => 764, 'title' => 'Bahçe', 'city_id' => 64],
            ['id' => 765, 'title' => 'Düziçi', 'city_id' => 64],
            ['id' => 766, 'title' => 'Hasanbeyli', 'city_id' => 64],
            ['id' => 767, 'title' => 'Kadirli', 'city_id' => 64],
            ['id' => 768, 'title' => 'Osmaniye', 'city_id' => 64],
            ['id' => 769, 'title' => 'Sumbas', 'city_id' => 64],
            ['id' => 770, 'title' => 'Toprakkale', 'city_id' => 64],
            ['id' => 771, 'title' => 'Ardeşen', 'city_id' => 65],
            ['id' => 772, 'title' => 'Çamlihemşin', 'city_id' => 65],
            ['id' => 773, 'title' => 'Çayeli', 'city_id' => 65],
            ['id' => 774, 'title' => 'Derepazari', 'city_id' => 65],
            ['id' => 775, 'title' => 'Findikli', 'city_id' => 65],
            ['id' => 776, 'title' => 'Güneysu', 'city_id' => 65],
            ['id' => 777, 'title' => 'Hemşin', 'city_id' => 65],
            ['id' => 778, 'title' => 'İkizdere', 'city_id' => 65],
            ['id' => 779, 'title' => 'İyidere', 'city_id' => 65],
            ['id' => 780, 'title' => 'Kalkandere', 'city_id' => 65],
            ['id' => 781, 'title' => 'Rize', 'city_id' => 65],
            ['id' => 782, 'title' => 'Pazar', 'city_id' => 65],
            ['id' => 783, 'title' => 'Adapazari', 'city_id' => 66],
            ['id' => 784, 'title' => 'Akyazi', 'city_id' => 66],
            ['id' => 785, 'title' => 'Arifiye', 'city_id' => 66],
            ['id' => 786, 'title' => 'Erenler', 'city_id' => 66],
            ['id' => 787, 'title' => 'Ferizli', 'city_id' => 66],
            ['id' => 788, 'title' => 'Geyve', 'city_id' => 66],
            ['id' => 789, 'title' => 'Hendek', 'city_id' => 66],
            ['id' => 790, 'title' => 'Karapürçek', 'city_id' => 66],
            ['id' => 791, 'title' => 'Karasu', 'city_id' => 66],
            ['id' => 792, 'title' => 'Kaynarca', 'city_id' => 66],
            ['id' => 793, 'title' => 'Kocaali', 'city_id' => 66],
            ['id' => 794, 'title' => 'Pamukova', 'city_id' => 66],
            ['id' => 795, 'title' => 'Sapanca', 'city_id' => 66],
            ['id' => 796, 'title' => 'Serdivan', 'city_id' => 66],
            ['id' => 797, 'title' => 'Söğütlü', 'city_id' => 66],
            ['id' => 798, 'title' => 'Tarakli', 'city_id' => 66],
            ['id' => 799, 'title' => '19 Mayis', 'city_id' => 67],
            ['id' => 800, 'title' => 'Alaçam', 'city_id' => 67],
            ['id' => 801, 'title' => 'Asarcik', 'city_id' => 67],
            ['id' => 802, 'title' => 'Atakum', 'city_id' => 67],
            ['id' => 803, 'title' => 'Ayvacik', 'city_id' => 67],
            ['id' => 804, 'title' => 'Bafra', 'city_id' => 67],
            ['id' => 805, 'title' => 'Canik', 'city_id' => 67],
            ['id' => 806, 'title' => 'Çarşamba', 'city_id' => 67],
            ['id' => 807, 'title' => 'Havza', 'city_id' => 67],
            ['id' => 808, 'title' => 'İlkadim', 'city_id' => 67],
            ['id' => 809, 'title' => 'Kavak', 'city_id' => 67],
            ['id' => 810, 'title' => 'Ladik', 'city_id' => 67],
            ['id' => 811, 'title' => 'Salipazari', 'city_id' => 67],
            ['id' => 812, 'title' => 'Tekkeköy', 'city_id' => 67],
            ['id' => 813, 'title' => 'Terme', 'city_id' => 67],
            ['id' => 814, 'title' => 'Vezirköprü', 'city_id' => 67],
            ['id' => 815, 'title' => 'Yakakent', 'city_id' => 67],
            ['id' => 816, 'title' => 'Akçakale', 'city_id' => 68],
            ['id' => 817, 'title' => 'Birecik', 'city_id' => 68],
            ['id' => 818, 'title' => 'Bozova', 'city_id' => 68],
            ['id' => 819, 'title' => 'Ceylanpinar', 'city_id' => 68],
            ['id' => 820, 'title' => 'Halfeti', 'city_id' => 68],
            ['id' => 821, 'title' => 'Harran', 'city_id' => 68],
            ['id' => 822, 'title' => 'Hilvan', 'city_id' => 68],
            ['id' => 823, 'title' => 'Şanliurfa', 'city_id' => 68],
            ['id' => 824, 'title' => 'Siverek', 'city_id' => 68],
            ['id' => 825, 'title' => 'Suruç', 'city_id' => 68],
            ['id' => 826, 'title' => 'Viranşehir', 'city_id' => 68],
            ['id' => 827, 'title' => 'Aydinlar', 'city_id' => 69],
            ['id' => 828, 'title' => 'Baykan', 'city_id' => 69],
            ['id' => 829, 'title' => 'Eruh', 'city_id' => 69],
            ['id' => 830, 'title' => 'Kurtalan', 'city_id' => 69],
            ['id' => 831, 'title' => 'Siirt', 'city_id' => 69],
            ['id' => 832, 'title' => 'Pervari', 'city_id' => 69],
            ['id' => 833, 'title' => 'Şirvan', 'city_id' => 69],
            ['id' => 834, 'title' => 'Ayancik', 'city_id' => 70],
            ['id' => 835, 'title' => 'Boyabat', 'city_id' => 70],
            ['id' => 836, 'title' => 'Dikmen', 'city_id' => 70],
            ['id' => 837, 'title' => 'Durağan', 'city_id' => 70],
            ['id' => 838, 'title' => 'Erfelek', 'city_id' => 70],
            ['id' => 839, 'title' => 'Gerze', 'city_id' => 70],
            ['id' => 840, 'title' => 'Sinop', 'city_id' => 70],
            ['id' => 841, 'title' => 'Saraydüzü', 'city_id' => 70],
            ['id' => 842, 'title' => 'Türkeli', 'city_id' => 70],
            ['id' => 843, 'title' => 'Beytüşşebap', 'city_id' => 71],
            ['id' => 844, 'title' => 'Cizre', 'city_id' => 71],
            ['id' => 845, 'title' => 'Güçlükonak', 'city_id' => 71],
            ['id' => 846, 'title' => 'İdil', 'city_id' => 71],
            ['id' => 847, 'title' => 'Şirnak', 'city_id' => 71],
            ['id' => 848, 'title' => 'Silopi', 'city_id' => 71],
            ['id' => 849, 'title' => 'Uludere', 'city_id' => 71],
            ['id' => 850, 'title' => 'Akincilar', 'city_id' => 72],
            ['id' => 851, 'title' => 'Altinyayla', 'city_id' => 72],
            ['id' => 852, 'title' => 'Divriği', 'city_id' => 72],
            ['id' => 853, 'title' => 'Doğanşar', 'city_id' => 72],
            ['id' => 854, 'title' => 'Gemerek', 'city_id' => 72],
            ['id' => 855, 'title' => 'Gölova', 'city_id' => 72],
            ['id' => 856, 'title' => 'Gürün', 'city_id' => 72],
            ['id' => 857, 'title' => 'Hafik', 'city_id' => 72],
            ['id' => 858, 'title' => 'İmranli', 'city_id' => 72],
            ['id' => 859, 'title' => 'Kangal', 'city_id' => 72],
            ['id' => 860, 'title' => 'Koyulhisar', 'city_id' => 72],
            ['id' => 861, 'title' => 'Sivas', 'city_id' => 72],
            ['id' => 862, 'title' => 'Şarkişla', 'city_id' => 72],
            ['id' => 863, 'title' => 'Suşehri', 'city_id' => 72],
            ['id' => 864, 'title' => 'Ulaş', 'city_id' => 72],
            ['id' => 865, 'title' => 'Yildizeli', 'city_id' => 72],
            ['id' => 866, 'title' => 'Zara', 'city_id' => 72],
            ['id' => 867, 'title' => 'Çerkezköy', 'city_id' => 73],
            ['id' => 868, 'title' => 'Çorlu', 'city_id' => 73],
            ['id' => 869, 'title' => 'Hayrabolu', 'city_id' => 73],
            ['id' => 870, 'title' => 'Malkara', 'city_id' => 73],
            ['id' => 871, 'title' => 'Marmara Ereğlisi', 'city_id' => 73],
            ['id' => 872, 'title' => 'Tekirdağ', 'city_id' => 73],
            ['id' => 873, 'title' => 'Muratli', 'city_id' => 73],
            ['id' => 874, 'title' => 'Saray', 'city_id' => 73],
            ['id' => 875, 'title' => 'Şarköy', 'city_id' => 73],
            ['id' => 876, 'title' => 'Almus', 'city_id' => 74],
            ['id' => 877, 'title' => 'Artova', 'city_id' => 74],
            ['id' => 878, 'title' => 'Başçiftlik', 'city_id' => 74],
            ['id' => 879, 'title' => 'Erbaa', 'city_id' => 74],
            ['id' => 880, 'title' => 'Tokat', 'city_id' => 74],
            ['id' => 881, 'title' => 'Niksar', 'city_id' => 74],
            ['id' => 882, 'title' => 'Pazar', 'city_id' => 74],
            ['id' => 883, 'title' => 'Reşadiye', 'city_id' => 74],
            ['id' => 884, 'title' => 'Sulusaray', 'city_id' => 74],
            ['id' => 885, 'title' => 'Turhal', 'city_id' => 74],
            ['id' => 886, 'title' => 'Yeşilyurt', 'city_id' => 74],
            ['id' => 887, 'title' => 'Zile', 'city_id' => 74],
            ['id' => 888, 'title' => 'Akçaabat', 'city_id' => 75],
            ['id' => 889, 'title' => 'Arakli', 'city_id' => 75],
            ['id' => 890, 'title' => 'Arsin', 'city_id' => 75],
            ['id' => 891, 'title' => 'Beşikdüzü', 'city_id' => 75],
            ['id' => 892, 'title' => 'Çarşibaşi', 'city_id' => 75],
            ['id' => 893, 'title' => 'Çaykara', 'city_id' => 75],
            ['id' => 894, 'title' => 'Dernekpazari', 'city_id' => 75],
            ['id' => 895, 'title' => 'Düzköy', 'city_id' => 75],
            ['id' => 896, 'title' => 'Hayrat', 'city_id' => 75],
            ['id' => 897, 'title' => 'Köprübaşi', 'city_id' => 75],
            ['id' => 898, 'title' => 'Maçka', 'city_id' => 75],
            ['id' => 899, 'title' => 'Trabzon', 'city_id' => 75],
            ['id' => 900, 'title' => 'Of', 'city_id' => 75],
            ['id' => 901, 'title' => 'Şalpazari', 'city_id' => 75],
            ['id' => 902, 'title' => 'Sürmene', 'city_id' => 75],
            ['id' => 903, 'title' => 'Tonya', 'city_id' => 75],
            ['id' => 904, 'title' => 'Vakfikebir', 'city_id' => 75],
            ['id' => 905, 'title' => 'Yomra', 'city_id' => 75],
            ['id' => 906, 'title' => 'Çemişgezek', 'city_id' => 76],
            ['id' => 907, 'title' => 'Hozat', 'city_id' => 76],
            ['id' => 908, 'title' => 'Mazgirt', 'city_id' => 76],
            ['id' => 909, 'title' => 'Tunceli', 'city_id' => 76],
            ['id' => 910, 'title' => 'Nazimiye', 'city_id' => 76],
            ['id' => 911, 'title' => 'Ovacik', 'city_id' => 76],
            ['id' => 912, 'title' => 'Pertek', 'city_id' => 76],
            ['id' => 913, 'title' => 'Pülümür', 'city_id' => 76],
            ['id' => 914, 'title' => 'Banaz', 'city_id' => 77],
            ['id' => 915, 'title' => 'Eşme', 'city_id' => 77],
            ['id' => 916, 'title' => 'Karahalli', 'city_id' => 77],
            ['id' => 917, 'title' => 'Uşak', 'city_id' => 77],
            ['id' => 918, 'title' => 'Sivasli', 'city_id' => 77],
            ['id' => 919, 'title' => 'Ulubey', 'city_id' => 77],
            ['id' => 920, 'title' => 'Bahçesaray', 'city_id' => 78],
            ['id' => 921, 'title' => 'Başkale', 'city_id' => 78],
            ['id' => 922, 'title' => 'Çaldiran', 'city_id' => 78],
            ['id' => 923, 'title' => 'Çatak', 'city_id' => 78],
            ['id' => 924, 'title' => 'Edremit', 'city_id' => 78],
            ['id' => 925, 'title' => 'Erciş', 'city_id' => 78],
            ['id' => 926, 'title' => 'Gevaş', 'city_id' => 78],
            ['id' => 927, 'title' => 'Gürpinar', 'city_id' => 78],
            ['id' => 928, 'title' => 'Van', 'city_id' => 78],
            ['id' => 929, 'title' => 'Muradiye', 'city_id' => 78],
            ['id' => 930, 'title' => 'Özalp', 'city_id' => 78],
            ['id' => 931, 'title' => 'Saray', 'city_id' => 78],
            ['id' => 932, 'title' => 'Altinova', 'city_id' => 79],
            ['id' => 933, 'title' => 'Armutlu', 'city_id' => 79],
            ['id' => 934, 'title' => 'Çiftlikköy', 'city_id' => 79],
            ['id' => 935, 'title' => 'Çinarcik', 'city_id' => 79],
            ['id' => 936, 'title' => 'Yalova', 'city_id' => 79],
            ['id' => 937, 'title' => 'Termal', 'city_id' => 79],
            ['id' => 938, 'title' => 'Akdağmadeni', 'city_id' => 80],
            ['id' => 939, 'title' => 'Aydincik', 'city_id' => 80],
            ['id' => 940, 'title' => 'Boğazliyan', 'city_id' => 80],
            ['id' => 941, 'title' => 'Çandir', 'city_id' => 80],
            ['id' => 942, 'title' => 'Çayiralan', 'city_id' => 80],
            ['id' => 943, 'title' => 'Çekerek', 'city_id' => 80],
            ['id' => 944, 'title' => 'Kadişehri', 'city_id' => 80],
            ['id' => 945, 'title' => 'Yozgat', 'city_id' => 80],
            ['id' => 946, 'title' => 'Saraykent', 'city_id' => 80],
            ['id' => 947, 'title' => 'Sarikaya', 'city_id' => 80],
            ['id' => 948, 'title' => 'Şefaatli', 'city_id' => 80],
            ['id' => 949, 'title' => 'Sorgun', 'city_id' => 80],
            ['id' => 950, 'title' => 'Yenifakili', 'city_id' => 80],
            ['id' => 951, 'title' => 'Yerköy', 'city_id' => 80],
            ['id' => 952, 'title' => 'Alapli', 'city_id' => 81],
            ['id' => 953, 'title' => 'Çaycuma', 'city_id' => 81],
            ['id' => 954, 'title' => 'Devrek', 'city_id' => 81],
            ['id' => 955, 'title' => 'Gökçebey', 'city_id' => 81],
            ['id' => 956, 'title' => 'Karadeniz Ereğli', 'city_id' => 81],
            ['id' => 957, 'title' => 'Zonguldak', 'city_id' => 81],
        ];

        foreach ($districts as $data) {
            County::create($data);
        }
    }
}
